### ISSUE TITLE
What's difference with solid/acl-check?

### ISSUE THREAD

**Issue by linonetwo** [o-network/web-access-control#4]
Who is using this lib?

**Comment by fabiancook** [comment]
This here is a typescript implementation of this file... https://github.com/solid/node-solid-server/blob/master/lib/acl-checker.js

The module can be used by anyone who is building a solid compatible implementation, I will soon be using this for my own implementation, and you can see an example of usage here: https://github.com/o-network/http-rdf/blob/master/examples/util/handle-acl.js#L55

**Comment by fabiancook** [comment]
Also, to completely answer your original question, this module utilizes solid/acl-check in the same way node-solid-server does.

**Comment by linonetwo** [comment]
Thank you for answering!
